### ISSUE TITLE
Using multiple SQL namespaces for a single DbContext

### ISSUE THREAD

**Issue by langdonx** [moozzyk/CodeFirstFunctions#10]
This line in `OnModelCreating` seems to make it so that a single `DbContext` can only use functions within a single SQL namespace.

        modelBuilder.Conventions.Add(new FunctionsConvention<MyContext>("dbo"));

I have a `DbContext` where I need to call TVFs in multiple namespaces (`"dbo."`, `"Common."`, etc) on the same database.  I tried circumventing this configuration, but I haven't gotten anything to work so far.

Mostly I get `[Type] cannot be resolved into a valid type or function.`

**Comment by moozzyk** [comment]
When you create a convention you provide the default database schema. You can override it per store function by using the `DbFunctionDetailsAttribute`. You can find an example [here](https://github.com/moozzyk/CodeFirstFunctions/blob/1349dea5fea16eab1be2d3841bc3aaf14b8f152e/CodeFirstStoreFunctionsTests/FunctionDiscoveryTests.cs#L39).
