### ISSUE TITLE
Support table value parameters

### ISSUE THREAD

**Issue by AndersMalmgren** [moozzyk/CodeFirstFunctions#11]
If you guys could extend this library with supporting table value parameters it would become such a amazing lift to EF6.x

I have created a function successfully and it joins with any IQueryable nicely. But I want to be able to send  a table value parameter to the function so that I can join the IQueryable against a (big)list of id's

**Comment by moozzyk** [comment]
TVP support is not going to happen. CodeFirstFunctions does not bypass EF (i.e. it does not use `ExecuteSqlCommand` to invoke store functions but plugs into EF model) and EF does not support TVPs. AFAIK there are no plans to add TVP support to EF. You may try work around this limitation by passing parameters as string/Xml and parse it on the server side.
