### ISSUE TITLE
Pass char parameter to function

### ISSUE THREAD

**Issue by michaelcsikos** [moozzyk/CodeFirstFunctions#12]
Is this possible?

Method signature:
`public IQueryable<string> Split(string value, char delimiter)`

Throws:
The type 'System.Char' of the parameter 'delimiter' of function 'Split' is invalid. Parameters can only be of a type that can be converted to an Edm scalar type.

**Comment by moozzyk** [comment]
EDM does not define the char type and there is no built-in mapping for `char`. I think you need to make delimiter string `instead` of `char`.
