### ISSUE TITLE
HasComputedColumnSql option in Entity Framework 6

### ISSUE THREAD

**Issue by slavisabozovic0** [moozzyk/CodeFirstFunctions#20]
Please,

does anyone know how to implement option HasComputedColumnSql from Fluent API in EF 6?

I have problem, because I have scalar function which result I have to bind in model builder to computed property. In EF Core that is easy, but I don't know how to achieve this in EF 6.

Please help.

Thank you.

**Comment by moozzyk** [comment]
I am not sure how this question is related to this library but one of the first search results points to this: https://stackoverflow.com/questions/15585330/calculated-column-in-ef-code-first

Closing.
