### ISSUE TITLE
Unit and integration tests

### ISSUE THREAD

**Issue by RubixRevenge** [moozzyk/CodeFirstFunctions#24]
Is it possible to unit test and/or integration test the behavior of the table-valued functions we define in the DbContext?

I follow a repository pattern and so created interfaces of my dbcontext and repository. In my unit test project I mocked the interfaces and tried to develop a hello world test for one of my table valued functions. Below is a snippet form my DbContext, where `Mia1A_SummaryBar` is the name of a table-valued function in my SQL Server database.

```
        public virtual DbSet<Mia1ASummaryBar> Mia1ASummaryBars { get; set; }

        [DbFunction("MiaFy19Context", "Mia1A_SummaryBar")]
        public virtual IQueryable<Mia1ASummaryBar> Mia1A_SummaryBar()
        {
            return ((IObjectContextAdapter)this).ObjectContext
                .CreateQuery<Mia1ASummaryBar>("MiaFy19Context.[Mia1A_SummaryBar]()");
        }
```

When I unit tested the IQueryable function, I got null when I know I should have gotten one result. 

Do you have any samples of unit and/or integration tests we could use as a guide to create our own tests? I'm on the unit testing learning curve, so please forgive me if I'm asking an obvious question.  Thank you?

**Comment by RubixRevenge** [comment]
After trying different coding possibilities, I found one that appears to stick.

I'm pasting a _brief_ summary of my approach in case it is useful for anyone with a similar question.

```
using System.Linq;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;

//namespace [redacted]
{
    [TestClass]
    public class MiaFy19RepositoryitTest
    {
        private static Mock<IMiaFy19Context> _mockContext;
        private IMiaFy19Repository _mockRepository;

        private IQueryable<Mia1ASummaryBar> _mia1SummaryBarData;

        /// <summary>
        /// 1. populate _mia1SummaryBarData via a static function with test data
        /// 2. mock the interface of your dbcontext
        /// 3. configure the dbcontext to output your #1
        /// 4. mock the interface of your repository
        /// </summary>
        [TestInitialize]
        public void TestInitialize()
        {
            _mia1SummaryBarData = RepositoryTestData.PopulateMia1ASummaryBar();
            _mockContext = new Mock<IMiaFy19Context>();
            _mockContext.Setup(m => m.Mia1A_SummaryBar()).Returns(_mia1SummaryBarData);
            _mockRepository=new MiaFy19Repository(_mockContext.Object);
        }

        [TestMethod]
        public void GetMia1ASummaryBar_GivenCampus_ReturnsSingleRecord ()
        {
            const string campus = "CRA";
            var list = _mockRepository.GetMia1ASummaryBar(campus);
            list.Should().HaveCount(1);
        }
    }
}
```

**Comment by moozzyk** [comment]
I am glad you found an answer to your question. Unfortunately writing unit tests for code that uses DbContext (and friends) is quite challenging and often it is just easier to mock at a higher level and write end-to-end tests to test functionality that extends EF.
