### ISSUE TITLE
Why does StoreFunctionBuilder need schema value?

### ISSUE THREAD

**Issue by Kation** [moozzyk/CodeFirstFunctions#25]
_Create_ method of _StoreFunctionBuilder_ will check __schema_ and _functionDescriptor.DatabaseSchema_ value to not be null.

But it could be null when we add an internal sql function.

Something like _JSON_VALUE_ function, when I commented codes skip check schema it works well.

**Comment by moozzyk** [comment]
For built-in functions try creating the stub [this way](https://github.com/moozzyk/CodeFirstFunctions/blob/2e7342afcd492598f60dd7e30e1ad5c980dfdeab/CodeFirstStoreFunctionsTests/E2ETests.cs#L235-L240) and then you should be able to use them [like this](https://github.com/moozzyk/CodeFirstFunctions/blob/2e7342afcd492598f60dd7e30e1ad5c980dfdeab/CodeFirstStoreFunctionsTests/E2ETests.cs#L790).

**Comment by Kation** [comment]
@moozzyk thanks, I'm missing that attribute.
