### ISSUE TITLE
Compatibility with EntityFrameworkWithHierarchyId

### ISSUE THREAD

**Issue by JRobinson333** [moozzyk/CodeFirstFunctions#28]
Pawel, how can this be compiled against the above dll in Visual Studio as per the link below:
https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/HierarchyId 

Installing the NuGet package and then building the project results in many errors e.g.
"The type 'EdmType' is defined in an assembly that is not referenced. You must add a reference to assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=6847f3395fc61b47'.

I have checked the App.config file correctly lists this PublicKeyToken:

  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=6847f3395fc61b47" requirePermission="false" />
  </configSections>

**Comment by JRobinson333** [comment]
The XML code hasn't pasted through onto GitHub - here is the line from App.config without tags:

section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=6847f3395fc61b47" requirePermission="false"

**Comment by JRobinson333** [comment]
I'd overlooked the fact that the errors were from the CodeFirstStoreFunctionTests project so will close this off. Always worth checking (!)

**Comment by moozzyk** [comment]
I guess the issue was that you removed a reference to the original EntityFramework NuGet package and added a reference to the EntityFrameworkHierarchyId only to the CodeFirstFunctions project but not the test project.
