### ISSUE TITLE
Problems with table and scalar store functions

### ISSUE THREAD

**Issue by tschennie** [moozzyk/CodeFirstFunctions#31]
I implemented EF6 code first for our project. We're using table and scalar store functions. So therefore I needed to implemented CodeFirstFunctions.

My table functions look like:
```
[DbFunction("MyContext", "my_function_name")]
public virtual IQueryable<my_function_name_Result> my_function_name(Nullable<int> id)
{
	return this.ObjectContext.CreateQuery<my_function_name_Result>(...);
}
```

My scalar functions look like:
```
[DbFunction("CodeFirstDatabaseSchema", "my_function_name")]
public static string my_function_name(Nullable<int> id)
{
    throw new NotImplementedException();
}
```

Within the OnModelCreating-method I added:
`modelBuilder.Conventions.Add(new FunctionsConvention<MyContext>("dbo"));`

But now I always getting following error:
**Scalar store functions must be decorated with the 'DbFunction' attribute with the 'CodeFirstDatabaseSchema' namespace.**

But my scalar store function are decorated like this. What's the problem?!

**Comment by moozzyk** [comment]
Your declaration looks correct which makes me think it can be a different function causing the problem. I guess it would be useful if the exception contained the function name. Can you create and post a minimal, complete repro for me to take a look?

**Comment by tschennie** [comment]
Oh it's a really big project with many functions, therefore it doesn't make sense to create a minimal repro for that..
Yes, it would be really useful, if the exception is more detailled and contained the function name. How can I do that?

**Comment by moozzyk** [comment]
I updated the code to print the function name in the exception. Can you upgrade the package to 1.1.3 and to see which function is causing the trouble?

**Comment by tschennie** [comment]
Ok now I know which function is the trouble. But this function is a table function and not a scalar function..

**Comment by moozzyk** [comment]
Can you show how this function is defined?

**Comment by tschennie** [comment]
In sql:
```
CREATE FUNCTION [dbo].[f1_adressarten] (@sprache_selected INTEGER, @sprache_default INTEGER) RETURNS Table AS RETURN ( 
                SELECT s.*, dbo.f1_getDesc(@sprache_selected, @sprache_default, (s.tabellen_schl), s.bezeichnung_schl) as bezeichnung_wl 
                FROM adressarten s )
```

**Comment by moozzyk** [comment]
I am sorry for not being clear. I need to see how the function is defined in your context to figure out why it is being treated as the a scalar function and not not as a table function.

**Comment by moozzyk** [comment]
Most likely the return type of this function is not `IQueryable<>`.

**Comment by tschennie** [comment]
Ah yes, I had an IEnumerable<>, but changed it to IQueryable<> and then get the error that there is no edm type for..

**Comment by moozzyk** [comment]
EF needs to have all the involved types in its model. By default it will add all the EntityTypes from DbSet properties. If your TVF returns a type that is not automatically (or otherwise) included you need to add it yourself. In the E2ETests there is the `GetAirports_ComplexType` stub for a TVF. It returns `IQueryable<Airport_ResultType>` but the `Airport_ResultType` is not in the model so it is explicitly added in the `OnModelCreating` method:

https://github.com/moozzyk/CodeFirstFunctions/blob/f69ca17e37e173db9db0014b8d7c4bdd0cc825e8/CodeFirstStoreFunctionsTests/E2ETests.cs#L65

**Comment by tschennie** [comment]
Yes this was it! Great, now it works without adding the scalar functions as well 👍

**Comment by moozzyk** [comment]
I am glad that this is now working for you!
