### ISSUE TITLE
Multiple Schema Support

### ISSUE THREAD

**Issue by jasonrichardcraig** [moozzyk/CodeFirstFunctions#32]
The examples use the dbo schema, I have several TVF's that are from different schemas; is this supported?

**Comment by moozzyk** [comment]
Have you tried using the `DbFunctionDetails` attribute with the `DatabaseSchema` property - something like this: 
https://github.com/moozzyk/CodeFirstFunctions/blob/5ada6e5aeae069129535d08f2f50e15c3d9dfda9/test/CodeFirstStoreFunctionsTests/FunctionDiscoveryTests.cs#L67

**Comment by jasonrichardcraig** [comment]
I will try it. BTW Is there a way I could send you a database to look at? It has composite keys that have a computed column (level) and hierarchyid, and a lot of things that break ef code first.

Jason
________________________________

**Comment by moozzyk** [comment]
I don't do consulting so I don't think I will be able to help there. Sorry!

**Comment by jasonrichardcraig** [comment]
No worries. Microsoft really Effed Me In The A (so to speak); SQL Server has supported hierarchyid, geometry, composite keys, unique keys with relationships etc. since 2008 and yet thier EF tooling still craps the bed and cany support "advanced" scenarios!

________________________________

**Comment by moozzyk** [comment]
Considering the question answered.
