### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by rmtexas** [moozzyk/CodeFirstFunctions#7]
I do  not consider this a bug, just an observation that I never ran across any warning for in documentation or blogs and which may throw some folks off trying to use the library.

When you join two TVFs in a Linq query and they both have an ObjectParameter of the same name, when Linq composes the query to SQL, parameter name collisions will occur and throw this error:

Additional information: A parameter named 'XYZ' already exists in the parameter collection. Parameter names must be unique in the parameter collection.

I'm wondering if this would merit having the ObjectContext or whatever mechanism it is under-the-hood that decides on generating names, to have it compose more unique names based on the ObjectParameter source properties.

**Comment by rmtexas** [comment]
This is a bit hairier than I first thought.
So taking my advice from above I defined t TVFs
A(schoolId, studentId)
B(schoolId, courseId)
C(schoolId, athleteId)

Because schoolId would name-collide, I changed it to

A(AschoolId, studentId)
B(BschoolId, courseId)
C(CschoolId, athleteId)

Now I can A JOIN B just fine. And I can C Join B just fine.

But (A Join B).Intersect((C Join B)) throw the name collision error because of the redundant ASchoolId parameters coming from both the joined queries.

The parameters collection needs to eliminate dupes before resolving/executing the query

**Comment by rmtexas** [comment]
For each TVF, I added a random Guid value to each of my ObjectParameters and got it all resolved. This is how I solved it:

        [DbFunction("PostcardsContext", "tvfFlowsStepsTags")]
        public IQueryable<FlowStepTags> tvfFlowsStepsTags(long? schoolId, long? flowstepId)
        {
            string p1 = "p" + Guid.NewGuid().ToString("N");
            string p2 = "p" + Guid.NewGuid().ToString("N");
            var schoolIdCodeParameter = schoolId.HasValue ? new ObjectParameter(p1 + "_schoolId", schoolId) : new ObjectParameter(p1 + "_schoolId", typeof(long));
            var flowstepIdCodeParameter = flowstepId.HasValue ? new ObjectParameter(p2 + "_flowstepId", flowstepId) : new ObjectParameter(p2 + "_flowstepId", typeof(long));

            return ((IObjectContextAdapter)this).ObjectContext
                .CreateQuery<FlowStepTags>(
                    string.Format("[{0}].{1}", GetType().Name,
                        string.Format("[tvfFlowsStepsTags](@{0}_schoolId,@{1}_flowstepId)",p1,p2)), schoolIdCodeParameter, flowstepIdCodeParameter);
        }

**Comment by moozzyk** [comment]
This is interesting. I have actually never encountered a case like yours but I have not seen many people (if at all) trying to join two TFVs. I guess once you have to do this it might be more common since related TVFs will likely have overlapping parameters. I am glad you found a reasonable workaround for this.

**Comment by danielloganking** [comment]
Just want to say that we have run into this and utilize a similar work around.
