### ISSUE TITLE
Cast function implementation

### ISSUE THREAD

**Issue by kcjhendriks** [moozzyk/CodeFirstFunctions#9]
Hello,

I am at a loss how to implement a standard SQL function that is not support by EF 6,
I can not find any example out there how to implement this
it is the function CAST(Code AS float)
I am planning to use it inside where and orderby clauses

So far I got this
`    public static class MySQLFunctions
    {
        /// <summary>Returns numaric data converted from string data.</summary>
        /// <returns>The input expression converted to a double.</returns>
        /// <param name="number">A numeric expression.</param>
        [DbFunction("SqlServer", "CAST")]
        [SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "number")]
        public static double CastToDouble(string number)
        {
            throw new NotSupportedException("Function can not be called directly");
        }
    }`

` IQueryable<Department> query = db.Departments;
query = query.OrderBy(item => SqlFunctions.IsNumeric(item.Code) == 1 ? 0 : 1).ThenBy(item => SqlFunctions.IsNumeric(item.Code) == 1 ? MySQLFunctions.CastToDouble(item.Code) : 0);
return query.ToList()`

Thanks in advance

**Comment by moozzyk** [comment]
The support for this has been added recently but this version has not shipped on NuGet yet.

**Comment by moozzyk** [comment]
@kcjhendriks - I just published a new version of the package on NuGet so you should be able to map CAST now.
